spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        use_sql_comments: ture
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        legacy_limit_handler: true
    open-in-view: true
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/cuberpin}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 400
      minimum-idle: 100
      connection-timeout: 2000
  main:
    allow-bean-definition-overriding: true
  endpoint:
    health:
      show-details: always


url:
  gift-card: http://localhost:8081
  nh-banking: https://developers.nonghyup.com

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

logging:
  level:
    root: info

jwt:
  secret-key: ${JWT_SECRET_KEY:asdjfklasdjkflasjdklf}
  access-expired-exp: ${JWT_ACCESS_EXP:7200000}
  refresh-expired-exp: ${JWT_REFRESH_EXP:604800000}
  header: ${JWT_HEADER:Authorization}
  prefix: ${JWT_PREFIX:Bearer }

server:
  tomcat:
    max-connections: 200
    accept-count: 100
    connection-timeout: 20000
  domain:
    front-domain: ${FRONT_LOCAL:http://localhost:3000}
    back-domain: ${BACK_LOCAL:http://localhost:8080}
  port: ${SERVER_PORT:8080}
store:
  client-id: ${STORE_CLIENT_ID}
  client-secret: ${STORE_CLIENT_SECRET}
sms:
  api-key: ${SMS_API_KEY}
  send-phone-number: ${SMS_SEND_PHONE_NUMBER}
  token-key: ${SMS_TOKEN_KEY}
  admin-number: ${SMS_ADMIN_NUMBER}
